#include "Player.h"
#include "genum.h"

#ifndef __CHARSERV_H__92364928374692837469283746239874__
#define __CHARSERV_H__92364928374692837469283746239874__

namespace klib
{
	GDEFINE_ENUM_TYPE(PLAYERSERV_COMMAND, int16_t);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 0, LOGIN				);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 1, LOGIN_SUCCESS		);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 2, LOGIN_FAIL			);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 3, REGISTER			);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 4, REGISTER_SUCCESS	);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 5, REGISTER_FAIL		);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 6, TAKEN_USERNAME		);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 7, PLAYER_GET			);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 8, PLAYER_SET			);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	 9, BUY					);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	10, SELL				);
	GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND,	11, RENAME				);
	//GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND, 12, );
	//GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND, 13, );
	//GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND, 14, );
	//GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND, 15, );
	//GDEFINE_ENUM_VALUE(PLAYERSERV_COMMAND, 16, );

	struct	SUserCredentials
	{
		std::string Username = "";
		std::string Password = "";
	};

	struct	SUser
	{
		SUserCredentials	Credentials		= {};
		uint64_t			RegisterDate	= 0;
		uint64_t			LastLogin		= 0;
		uint64_t			FailedAttempts	= 0;
	};

	struct SPlayerServer
	{
		std::vector<klib::SPlayer>	Players;
		std::vector<std::string>	Log;
		time_t						Time;
	};
}

#endif // __CHARSERV_H__92364928374692837469283746239874__
