#include <string>

#ifndef __CREDITS_H__230984729380740298374092837423__
#define __CREDITS_H__230984729380740298374092837423__

namespace klib
{
	static const std::string namesSpecialThanks[] =
	{	"-- Loosely based on homework code and idea by --"	
	,	"Nethrim"					
	,	""							
	,	"-- Programming --"			
	,	"654"						
	,	""							
	,	"-- Testers --"				
	,	"Gorby"						
	,	"Nethrim"					
	,	""							
	,	"-- Everything else --"		
	,	"654"						
	,	""							
	,	"-- Special Thanks to --"	
	,	"Nethrim"	
	,	"Gorby"		
	,	"Andrew"	
	,	"James"		
	,	"Suelika"	
	,	"Paul"		
	,	"Bill"		
	,	"Matt"		
	,	"Robert"	
	,	"Riva"		
	,	"Pia"		
	,	"David"		
	,	"Stuart"	
	,	"Nhi"		
	,	"Andy"		
	,	"Esteban"	
	,	"Chi-Wei"	
	,	"Michael"	
	,	"Serguei"	
	,	"Henry"		
	,	"Kirk"		
	,	"Gabriela"	
	,	"Jeff"		
	,	"Marc"		
	,	"Jose"		
	,	"Jose"		
	,	"Zach"		
	,	"Anson"		
	,	"Vitaliy"	
	,	"Emily"		
	,	"Cara"		
	,	"Brent"		
	,	"Fredrik"	
	,	"Adan"		
	,	"Ted"		
	,	"Terran"	
	,	"Nicolas"	
	,	"Nicolas"	
	,	"Martin"	
	,	"Mauro"		
	,	"Luis"		
	,	"Carlos"	
	,	"Atul"		
	,	""									
	,	""									
	,	"Have a nice weekend!"				
	,	""									
	,	""									
	,	"Press ESC to return to main menu."	
	};
}

#endif // __CREDITS_H__230984729380740298374092837423__
